### ISSUE TITLE
Possible things to add

### ISSUE THREAD

**Issue by mitchlloyd** [201-created/pear#1]
Thought I would create an issue before doing a PR so that I make sure I'm not duplicating anything or stomping on other functionality. 
- bash alias: `es` to ember serve. I also have an `es!` script in `bin` that kills any other running ember processes before starting a new one.
- I use comma for my leader key. I think we can add a mapping with `:nmap , ;` if there are no conflicts with this.
- I use ctrl-n to toggle NERDTree
- I use a plugin called [yank-stack](https://github.com/maxbrunsfeld/vim-yankstack) that keeps a list of things you've yanked.
- I use leader, leader to switch between last buffer (you guys have `<leader> s`). Not really dead set on that one.

**Comment by bantic** [comment]
> bash alias: es to ember serve. I also have an es! script in bin that kills any other running ember processes before starting a new one.

+1

> I use comma for my leader key. I think we can add a mapping with :nmap , ; if there are no conflicts with this.

Do you mean two keys that both function as leader? That seems fine to me, I don't think I use it.

> ctr-n to toggle NERDTree

I use leader-d (`;d`). `ctr-n` is currently mapped to [vim multiple cursors](https://github.com/terryma/vim-multiple-cursors), so that may be a conflict.

> I use leader, leader to switch between last buffer (you guys have <leader> s). Not really dead set on that one.

You mean, since comma is your leader, you type `,,` ? I'm not opposed to having both mappings.

**Comment by bantic** [comment]
Yank-stack looks cool, I'm +1 to adding it

**Comment by mitchlloyd** [comment]
Opened a PR: #2.
